### ISSUE TITLE
jupyter-marimo-proxy with jupyter docker-stacks images

### ISSUE THREAD

**Issue by legout** [jyio/jupyter-marimo-proxy#6]
Hi,

I´m am trying to get jupyter-marimo-proxy running with any of the [jupyter docker stackes](https://github.com/jupyter/docker-stacks) images.

I have a very simple Dockerfile

```Dockerfile
FROM  quay.io/jupyter/base-notebook

RUN   pip install --no-cache-dir 'marimo>=0.6.21'
RUN   /opt/conda/bin/pip install https://github.com/jyio/jupyter-marimo-proxy/archive/main.zip
```

Unfortunately, there is no marimo icon after building the image and running the container.

![image](https://github.com/user-attachments/assets/a51e12a5-a568-4e86-9e40-ab66c772112b)

**Comment by benz0li** [comment]
@legout Try https://github.com/b-data/jupyterlab-r-docker-stack#marimo on https://demo.jupyter.b-data.ch

Do not forget to restart the container. You can do so at https://demo.jupyter.b-data.ch/hub/home.

Cross reference:

* https://github.com/jyio/jupyter-marimo-proxy/issues/1

**Comment by legout** [comment]
@benz0li 
Unfortunately it is not as simple :-)

I mounted a volume to /home/jovyan, to persist the user data, run the commands from here https://github.com/b-data/jupyterlab-r-docker-stack#marimo and restarted the container. No success.

The problem seems to be, `which pip` gives me `/opt/conda/bin/pip` and therefore marimo and jupyter-marimo-proxy is not installed persistent in /home/jovyan

**Comment by benz0li** [comment]
@legout I am not using the [Jupyter docker stack](https://github.com/jupyter/docker-stacks), but [b-data](https://github.com/b-data)'s/my own  [Jupyter](https://github.com/b-data/jupyterlab-mojo-docker-stack)[Lab](https://github.com/b-data/jupyterlab-julia-docker-stack) [docker](https://github.com/b-data/jupyterlab-python-docker-stack) [stacks](https://github.com/b-data/jupyterlab-r-docker-stack):

> 1. Multi-arch: `linux/amd64`, `linux/arm64/v8`  
>    :information_source: Runs on Apple M series using Docker Desktop.
> 1. Base image: [Debian](https://hub.docker.com/_/debian) instead of [Ubuntu](https://hub.docker.com/_/ubuntu)  
>    :information_source: CUDA-based images use Ubuntu.
> 1. IDE: [code-server](https://github.com/coder/code-server) next to [JupyterLab](https://github.com/jupyterlab/jupyterlab)  
>    :information_source: code-server = [`Code - OSS`](https://github.com/microsoft/vscode) in the browser.
> 1. Just Python – no [Conda](https://github.com/conda/conda) / [Mamba](https://github.com/mamba-org/mamba)

– https://github.com/b-data/jupyterlab-python-docker-stack#similar-projects

**Comment by legout** [comment]
Thanks. I´ll give it a try!

**Comment by legout** [comment]
No success

This is what I did

1. Started the container

```bash
docker run -it --rm \y
  -p 8888:8888 \
  -u root \
  -v "${PWD}/jupyterlab-jovyan":/home/jovyan \
  -e NB_UID=$(id -u) \
  -e NB_GID=$(id -g) \
  -e CHOWN_HOME=yes \
  -e CHOWN_HOME_OPTS='-R' \
   glcr.b-data.ch/jupyterlab/r/base
```

2. In Jupyterlab, started a terminal

```bash
pip install marimo click
pip install git+https://github.com/b-data/jupyter-marimo-proxy.git@jupyterlab-docker-stack
```

3. Restarted the container

There is still no marimo icon
![image](https://github.com/user-attachments/assets/c7ab4653-ec20-40a3-b1e1-ec80d0bf50cd)

**Comment by benz0li** [comment]
For some reason, neither the original `jupyter-marimo-proxy` nor [b-data's/my fork](https://github.com/b-data/jupyterlab-r-docker-stack#marimo) seem to work.

I will not investigate further, though.

**Comment by legout** [comment]
Now its working.

Basically, thats what I´ve done.

```dockerfile
FROM quay.io/jupyter/base-notebook
...
RUN conda install jupyter-server-proxy jupyter-vscode-proxy jupyterlab-git marimo -y && \
    /opt/conda/bin/pip install --no-cache-dir jupyter-marimo-proxy
...
````

**Comment by benz0li** [comment]
@legout It works again on https://demo.jupyter.b-data.ch.

**Comment by legout** [comment]
What did you do to get it back working?

**Comment by benz0li** [comment]
> What did you do to get it back working?

To get it working without an associated JupyterHub: https://github.com/b-data/jupyter-marimo-proxy/commit/378ccc1c29c7f3a8b6ea9200cb90849ad0b39276
